### ISSUE TITLE
Xiaomi Air Purifier 3 - No AQI / RPS or other data

### ISSUE THREAD

**Issue by austwhite** [denysdovhan/purifier-card#71]
**Before submitting a bug**

[ x] I updated to the latest version available
[ x] I cleared the cache of my browser

**Describe the bug**

In Home Assistant 2021.9.7 it seems that the Attribute have been broken out into separate sensor entities when using the Xiaomi Miio integration, meaning that the AQI, motor speed, filter percentage and other data is no longer displaying in this card.
I am not sure if this only affects Air Purifier 3 /3H or if others are affected, but I noticed the change recently.
Instead of AQI, Filter % etc being attributes of the fan.xxxxx entity, they seem to be broken out to separate sensors as in sensor.xxxx_pm2.5, sensor.xxxxx_filter_life etc etc.

**Steps to reproduce**

1. Removed integration
2. Reinstalled using Integration in Home Assistant
3. Options still broken out as sensors and not as attributes of the fan.xxxx entity
4. No data in Air Purifier Card

**Expected behavior**
To see data in the air purifier card

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: [e.g. 0.13.0]
- Browser: [e.g. Google Chrome, (desktop and mobile) and Microsoft Edge (Chromium base, new version).
- HomeAssistant version: [e.g 2021.9.7]

**Comment by xury77** [comment]
Because attributes now become entities.  I managed customize some of entities:
`type: vertical-stack
in_card: true
cards:
  - type: entities
    no_card: true
    title: Powietrze w domu
    show_header_toggle: false
    state_color: true
    entities:
      - fan.air_purifier_2
      - sensor.air_purifier_pm2_5
      - sensor.air_purifier_humidity
      - sensor.air_purifier_temperature
  - type: custom:purifier-card
    entity: fan.air_purifier_2
    aqi:
      - entity_id: sensor.air_purifier_pm2_5
    stats:
      - entity_id: sensor.air_purifier_filter_life_remaining
        subtitle: Pozostało filtra
        unit: '%'
      - entity_id: sensor.air_purifier_motor_speed
        unit: RPM
        subtitle: Obroty
      - entity_id: sensor.air_purifier_temperature
        unit: C
        subtitle: Temperatura
    actions:
      - name: Cicho
        icon: mdi:weather-night
        speed: Silent
      - name: 25%
        icon: mdi:circle-slice-2
        speed: Favorite
        xiaomi_miio_favorite_level: 3
      - name: 50%
        icon: mdi:circle-slice-4
        speed: Favorite
        xiaomi_miio_favorite_level: 7
      - name: 75%
        icon: mdi:circle-slice-6
        speed: Favorite
        xiaomi_miio_favorite_level: 10
      - name: 100%
        icon: mdi:circle-slice-8
        speed: Favorite
        xiaomi_miio_favorite_level: 14
      - name: Auto
        icon: mdi:brightness-auto
        speed: Auto
show_name: true
show_status: true
show_state: true
show_toolbar: true
compact_view: false
`
But it does not work for aqi object.

**Comment by austwhite** [comment]
AQI is probably most important one to me.
Thanks for the work around for some other sensors.   I noticed AQI is broken out as sensor.xxxx_pm2.5.   Might have to play with it until a proper fix is put in place

**Comment by PonyOny** [comment]
I'm facing the same issue, the problem with AQI not showing after setting the entity_id is because the way it's setting the value in code, when you set aqui in the config it's an array and the way it's trying to assigning the property is not accesión the array value, it's trying to map an object property.
![Screenshot_1](https://user-images.githubusercontent.com/17080292/136651873-2ec3df90-3222-464d-b376-093d7f781a4c.png)

![Screenshot_2](https://user-images.githubusercontent.com/17080292/136651874-5594ce35-8a99-4004-ac4c-9970e99b2072.png)

**Comment by austwhite** [comment]
Just noting this issue is still very much present, just to stop the stalebot grabbing it.

**Comment by blacksheepinc** [comment]
> 
> 
> Just noting this issue is still very much present, just to stop the stalebot grabbing it.

Try this modification:
https://github.com/blacksheepinc/purifier-card/tree/master/dist

![kép](https://user-images.githubusercontent.com/397624/140035464-cc6d9b6a-6fdb-48d6-bd3e-f6c77671ecfa.png)

**Comment by xury77** [comment]
Hi blacksheepinc 
How to install your repo?
I installed by custom url but no purifer card visible on the dashboard.

**Comment by blacksheepinc** [comment]
> Hi blacksheepinc How to install your repo? I installed by custom url but no purifer card visible on the dashboard.

I think the easiest would be install from HACS, then change the purifier-card.js from this link (https://github.com/blacksheepinc/purifier-card/blob/master/dist/purifier-card.js), with some file editor or samba plugin.

**Comment by xury77** [comment]
I tried this way too and also does not work.

**Comment by Yersi88** [comment]
Same here AQI displays no data if entity is provided. This needs fixing ;-;

**Comment by Yersi88** [comment]
> > Hi blacksheepinc How to install your repo? I installed by custom url but no purifer card visible on the dashboard.
> 
> I think the easiest would be install from HACS, then change the purifier-card.js from this link (https://github.com/blacksheepinc/purifier-card/blob/master/dist/purifier-card.js), with some file editor or samba plugin.

This link doesn't work anymore :(

**Comment by austwhite** [comment]
This project seems to have gone stale with no updates recently.  It is a shame as I have not found anything like it.
Unfortunately blacksheepinc seems to have pulled down their modification of the card also

**Comment by denysdovhan** [comment]
@xury77 you have mistake in your config over here:

```yaml
aqi:
  - entity_id: sensor.air_purifier_pm2_5
```

it must be an object, not an array:

```yaml
aqi:
  entity_id: sensor.air_purifier_pm2_5
  unit: µg/m³
```

**Comment by denysdovhan** [comment]
Folks, I don't see any problem or a bug in the card. The only thing I see in this issue is a common typo you all did.

`aqi` is an **object**, not a **list**. You should not use `-` when specifying `entity_id` for `aqi` object.

I use Xiaomi Air Purifier 3H, it also exposes pollution data as a sensor. Here's my config that works completely fine:

```yaml
type: custom:purifier-card
entity: fan.air_purifier
show_name: false
show_state: false
aqi:
  entity_id: sensor.air_purifier_pm2_5
  unit: µg/m³
shortcuts:
  - name: Silent
    icon: mdi:weather-night
    speed: Silent
  - name: 25%
    icon: mdi:circle-slice-2
    speed: Favorite
    xiaomi_miio_favorite_level: 3
  - name: 50%
    icon: mdi:circle-slice-4
    speed: Favorite
    xiaomi_miio_favorite_level: 7
  - name: 75%
    icon: mdi:circle-slice-6
    speed: Favorite
    xiaomi_miio_favorite_level: 10
  - name: 100%
    icon: mdi:circle-slice-8
    speed: Favorite
    xiaomi_miio_favorite_level: 14
  - name: Auto
    icon: mdi:brightness-auto
    speed: Auto
stats:
  - entity_id: sensor.air_purifier_filter_life_remaining
    unit: '%'
    subtitle: Залишок фільтру
  - entity_id: sensor.air_purifier_motor_speed
    unit: Об/с
    subtitle: Швидкість мотору
  - entity_id: sensor.air_purifier_filter_use
    unit: год
    subtitle: Залишок фільтру
show_toolbar: true
```

**Comment by xury77** [comment]
Yes. You have to  only remove  a dash before entity_id:

**Comment by PonyOny** [comment]
Thanks, than worked perfect

**Comment by denysdovhan** [comment]
@austwhite you don't have to spread panic around.

When the project doesn't have constant changes it is not _stale_, it is _stable_ and _mature_. Having more than 4.5K users, it's important to carefully pick what changes are introduced. I can't please everyone, so I must pick what needs to be done.

Also, don't forget that I don't owe anything to anyone. I published my work **for free, for everyone**. Only a small fraction of those 4.5K users [have donated at least something for my work](https://www.buymeacoffee.com/denysdovhan).

Remember, I still have my personal life and my permanent job. If you need any specific changes, feel free to open a PR or fork this repo — the license allows that.

Let's maintain a healthy OSS culture, instead of pushing each other. Take care!

**Comment by austwhite** [comment]
@denysdovhan   I have not donated to your project yet, but I do donate to many opensource projects when I continue using them.
I appreciate the information and pointing out our error, and this indeed does fix the AQI issue.  
I am still having issues where the shortcut buttons do not work, but that may be another thing to deal with.
When using the below code for shortcuts, Home Assistant throws a failed to call service error and I get this in the logs.  The log 
This may need another issue though

`Logger: homeassistant.components.fan
Source: components/fan/__init__.py:246
Integration: Fan (documentation, issues)
First occurred: November 30, 2021, 7:59:25 PM (37 occurrences)
Last logged: 6:04:41 AM

The fan.set_speed service is deprecated, use fan.set_percentage or fan.set_preset_mode instead`

`shortcuts:
  - name: Silent
    icon: mdi:weather-night
    speed: Silent
  - name: 25%
    icon: mdi:circle-slice-2
    speed: Favorite
    xiaomi_miio_favorite_level: 3
  - name: 50%
    icon: mdi:circle-slice-4
    speed: Favorite
    xiaomi_miio_favorite_level: 7
  - name: 75%
    icon: mdi:circle-slice-6
    speed: Favorite
    xiaomi_miio_favorite_level: 10
  - name: 100%
    icon: mdi:circle-slice-8
    speed: Favorite
    xiaomi_miio_favorite_level: 14
  - name: Auto
    icon: mdi:brightness-auto
    speed: Auto`

**Comment by denysdovhan** [comment]
@austwhite this might be an actual bug that needs to be fixed. We need to migrate `fan.set_speed` to new counterparts.

**Comment by austwhite** [comment]
@denysdovhan   Did you need a new issue for that one, or can you work off the information I just gave?
